### ISSUE TITLE
v1.3.0 and v1.3.1 missing from conda-forge?

### ISSUE THREAD

**Issue by cschnaible** [conda-forge/lmfit-feedstock#46]
### Comment:

conda forge lists only [v1.2.2](https://anaconda.org/conda-forge/lmfit/).

What can be done to get versions >1.2.2 on conda-forge?

**Comment by newville** [comment]
@cschnaible Thanks for the reminder. This should be fixed with #45 merged now.

**Comment by cschnaible** [comment]
👏  thanks!

**Comment by cschnaible** [comment]
seems like the build pipeline failed?
https://github.com/conda-forge/lmfit-feedstock/runs/26489821332

**Comment by newville** [comment]
@cschnaible oh, it looks like the recipe must be out of date...  I'll look into it.

**Comment by newville** [comment]
@cschnaible OK, it now looks to be uploaded!  https://anaconda.org/conda-forge/lmfit/files
