### ISSUE TITLE
Travis CI canceled?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/lmfit-feedstock#5]
Just FYI appears Travis CI was canceled on `master`.

**Comment by ericdill** [comment]
That is really strange that it is showing as cancelled since it appears to actually still be running (https://travis-ci.org/conda-forge/lmfit-feedstock/jobs/150972212)

**Comment by ericdill** [comment]
FWIW I also see is as being "cancelled"

**Comment by jakirkham** [comment]
Indeed it appears to have run through canceled. Very odd.
